Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeOut: 60
  WriteTimeOut: 60

APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads           # 上传文件的最终保存路径
  UploadServerUrl: http://127.0.0.1:8000/static       # 上传文件后用于展示的文件服务地址
  UploadImageMaxSize: 5     # MB  上传文件允许的最大空间大小
  UploadImageAllowExts:     # 上传文件所允许的文件后缀
    - .jpg
    - .jpeg
    - .png

JWT:
  Secret: nanjingblue
  Issuer: blog-service
  Expire: 7200

Database:
  DBType: mysql
  Username: root
  Password: 212134
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 592671041@qq.com
  Password: hello.world.7
  IsSSL: true
  From: 592671041@qq.com
  To:
    - 1738308397@qq.com